### ISSUE TITLE
Can't obtain storage access

### ISSUE THREAD

**Issue by tw0xa** [devgianlu/Aria2App#280] opened 2023-08-03 08:00 UTC
I am currently using LineageOS 20, Android 13. Lastest release of Aria2App
I can't give storage permission to app and it throws an error every time I launch it. 
![Screenshot_20230803-105254_Trebuchet](https://github.com/devgianlu/Aria2App/assets/98216123/5ba6225b-fb4c-4d63-9be8-4f597a23dc98)

**Comment by tw0xa** [comment] 2023-08-03 08:03
There is no problem at version 5.9.12
![Screenshot_20230803-110207_Trebuchet](https://github.com/devgianlu/Aria2App/assets/98216123/2aac8020-b416-4ef0-a900-0b8353f9e0c6)

**Comment by devgianlu** [comment] 2023-08-26 08:25
Duplicate of #271

**Closed by devgianlu** 2023-08-26 08:25 UTC
