### ISSUE TITLE
URI doesn't get added in first go

### ISSUE THREAD

**Issue by hallowedbethyname** [devgianlu/Aria2App#72] opened 2019-07-02 15:49 UTC
![Screenshot_20190702-201544_Aria2App](https://user-images.githubusercontent.com/52462034/60526739-6d304c80-9ce0-11e9-9fc9-ba52d212ae30.png)
The service is off. You choose Aria2App to download a file from the browser. Dismiss the Webview prompt. URI is auto filled from the clipboard. Add it. Try to start the download.

The toast in the image above appears.

Try to go back. The add URI box appears again. This time when you add it, the download starts successfully.

**Comment by devgianlu** [comment] 2019-07-07 14:24
I couldn't reproduce this issue with version 5.1.6, could you try again?

**Comment by devgianlu** [comment] 2019-07-08 09:08
I've released version `5.1.7`, hopefully this will do it.

**Comment by hallowedbethyname** [comment] 2019-07-10 16:11
The bug exists in 5.1.7.

**Comment by devgianlu** [comment] 2019-07-19 08:37
Fixed with eb833345f72dfdbc9c64c5a809b5a4e5bd511f9c. The issue was caused by the dark mode.

**Closed by devgianlu** 2019-07-19 08:37 UTC
Labels: bug

**Comment by opusforlife2** [comment] 2019-07-22 11:10
Wow. What a quaint bug. xD

I can confirm it is fixed in 5.1.8. Thanks!
