### ISSUE TITLE
Bugs in aria2APP

### ISSUE THREAD

**Issue by biange200** [devgianlu/Aria2App#274] opened 2023-06-28 03:36 UTC
Previously, I downloaded and installed version 5.9.13 directly, but this version was unable to obtain storage access, and I tried several times but it didn't work
![Screenshot_20230628_081000.jpg](https://github.com/devgianlu/Aria2App/assets/37582806/708ad6e7-999a-49b0-b4b4-f208461be969)

It occurred to me that it could be a version issue. I then downloaded and installed 5.9.12 and I was able to open the app normally

![Screenshot_20230628_113600.jpg](https://github.com/devgianlu/Aria2App/assets/37582806/587af80c-9f35-4de0-8e3f-c4113525b6d4)

**Comment by FandonGeek** [comment] 2023-07-28 15:31
having the same question, using OnePlus Ace2 with colorOS based on android 13

**Comment by biange200** [comment] 2023-08-02 22:59
> having the same problem, using OnePlus Ace2 with colorOS based on android 13

Vivo is also like this

**Comment by devgianlu** [comment] 2023-08-26 08:25
Duplicate of #271

**Closed by devgianlu** 2023-08-26 08:25 UTC
