### ISSUE TITLE
Latest version white screen

### ISSUE THREAD

**Issue by zhengqwe** [devgianlu/Aria2App#330] opened 2024-09-13 11:03 UTC
Latest version white screen. Uninstall and install again not work.
Device: Redmi Note 9 Pro, Android 12

**Comment by devgianlu** [comment] 2024-09-13 11:25
I am unable to reproduce this behaviour. Do you have any stacktrace/log?

**Comment by Recognizer83** [comment] 2024-09-14 00:35
having same issue

**Comment by abskmj** [comment] 2024-09-14 04:29
Same issue. App is stuck in loading screen. Android 14.

**Comment by devgianlu** [comment] 2024-09-14 14:32
@NielSync are you able to get a stacktrace of the exception causing the ANR?

**Comment by devgianlu** [comment] 2024-09-14 16:23
Should be fixed in the latest release (5.9.18). Feel free to re-open if you still have problems.

**Closed by devgianlu** 2024-09-14 16:23 UTC
