### ISSUE TITLE
Improve support on Chromebooks

### ISSUE THREAD

**Issue by wallace11** [devgianlu/Aria2App#3] opened 2018-10-21 21:55 UTC
Hi,
I just happened to check the app on my Chromebook running the latest 59 version (with Android apps support).
I noticed two strange behaviors related to the DirectDownload menu:

1. When the app is in full screen mode go to files on any download item -> click on the item -> the menu appears to show but it doesn't. The issue is resolved once the window is resized to phone size.
2. This is a direct continue to the previous one: while in phone size mode the button actually shows and the download starts, but when it gets to 100% it just fails. 

I do not know if you own a Chromebook so testing on it might be difficult. I can help testing the fix if needed.

Cheers.

**Comment by devgianlu** [comment] 2018-10-22 05:13
These issue may be affecting all devices. I'll check.

**Comment by devgianlu** [comment] 2018-10-25 13:01
Can you send me a screenshot of the first issue?

I've also opened #4 because I'm going to use an external library to download stuff.

**Comment by wallace11** [comment] 2018-10-25 13:21
The first issue is very weird.
I discovered that there are actually 3 different "states" I can get it to be in:
- Click/tap a file -> Nothing shows
- Click/tap a file -> Go to a different app -> Go back -> Partly shown
- Click/tap a file -> Swipe from bottom (up to around 1/5 of the screen height) -> Partly shown but misplaced

Attaching screenshots in the mentioned order:
![screenshot 2018-10-25 at 22 13 40](https://user-images.githubusercontent.com/5497761/47503062-2d3cde00-d8a4-11e8-8d21-d7deca8e7b49.png)
![screenshot 2018-10-25 at 22 14 02](https://user-images.githubusercontent.com/5497761/47503063-2dd57480-d8a4-11e8-9ae8-5ccc88ada7ec.png)
![screenshot 2018-10-25 at 22 14 39](https://user-images.githubusercontent.com/5497761/47503064-2dd57480-d8a4-11e8-8af0-b03837f47850.png)

**Comment by devgianlu** [comment] 2018-10-27 05:32
This is marked as intended behavior, but it's clearly not. Hopefully I can change some resources to make it bigger on tablets

**Comment by devgianlu** [comment] 2018-10-29 14:03
Fixed in [devgianlu/CommonUtils](https://github.com/devgianlu/CommonUtils).

**Closed by devgianlu** 2018-10-29 14:03 UTC
Labels: bug
